Fix query to handle multiple values block
NCATS-Tangerine/cam-kp-api pull request #312
Opened 2021-06-14 18:25 UTC by Shalsh23

2021-06-17 16:53 UTC, jdr0887 approved these changes

2021-06-18 15:46 UTC, jdr0887 requested changes
please leave logging in there

2021-06-18 15:48 UTC, jdr0887 approved these changes

2021-06-18 15:51 UTC, jdr0887 approved these changes

2021-06-18 19:37 UTC, Shalsh23 commented
Test 1:

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
            "NCBIGene:2036","NCBIGene:1431","NCBIGene:79132","NCBIGene:3633","NCBIGene:6262","NCBIGene:283659","NCBIGene:89870","NCBIGene:9487","NCBIGene:7802","NCBIGene:57787","NCBIGene:255738","NCBIGene:2057","NCBIGene:144717","NCBIGene:10019","NCBIGene:2335","NCBIGene:23076","NCBIGene:7917","NCBIGene:64288","NCBIGene:11018","NCBIGene:8343","NCBIGene:10428","NCBIGene:10384","NCBIGene:84081","NCBIGene:25980","NCBIGene:6521","NCBIGene:7155","NCBIGene:4855","NCBIGene:993","NCBIGene:163486","NCBIGene:4088","NCBIGene:2275","NCBIGene:5926","NCBIGene:27030","NCBIGene:1674","NCBIGene:256364","NCBIGene:51385","NCBIGene:440603","NCBIGene:6941","NCBIGene:57188","NCBIGene:375056","NCBIGene:54887","NCBIGene:783","NCBIGene:84217","NCBIGene:55204","NCBIGene:6546","NCBIGene:60678","NCBIGene:152273","NCBIGene:10203","NCBIGene:100507679","NCBIGene:1021","NCBIGene:11060","NCBIGene:57057","NCBIGene:7456","NCBIGene:149345","NCBIGene:4952","NCBIGene:23132","NCBIGene:22852","NCBIGene:1605","NCBIGene:79800","NCBIGene:90324","NCBIGene:219469","NCBIGene:8542","NCBIGene:8927","NCBIGene:2250","NCBIGene:144100","NCBIGene:10642","NCBIGene:80304","NCBIGene:57679","NCBIGene:3621","NCBIGene:25894","NCBIGene:57176","NCBIGene:2122","NCBIGene:23499","NCBIGene:4439","NCBIGene:5175","NCBIGene:641649","NCBIGene:80736","NCBIGene:25865","NCBIGene:1460","NCBIGene:1029","NCBIGene:4485","NCBIGene:1138","NCBIGene:130026","NCBIGene:80345","NCBIGene:284058","NCBIGene:5350","NCBIGene:629","NCBIGene:119032","NCBIGene:79893","NCBIGene:56658","NCBIGene:162540","NCBIGene:1244","NCBIGene:23403","NCBIGene:7871","NCBIGene:9564","NCBIGene:4277","NCBIGene:8654","NCBIGene:2321","NCBIGene:54205","NCBIGene:55297","NCBIGene:349149","NCBIGene:84811","NCBIGene:23047","NCBIGene:148362","NCBIGene:64853","NCBIGene:9457","NCBIGene:23149","NCBIGene:114971","NCBIGene:3360","NCBIGene:10291","NCBIGene:23328","NCBIGene:7586","NCBIGene:23245","NCBIGene:4023","NCBIGene:55785","NCBIGene:51168","NCBIGene:165082","NCBIGene:135","NCBIGene:146212","NCBIGene:9785","NCBIGene:8407","NCBIGene:135656","NCBIGene:7726","NCBIGene:79991","NCBIGene:643314","NCBIGene:10456","NCBIGene:4625","NCBIGene:101929256","NCBIGene:401250","NCBIGene:84332","NCBIGene:563","NCBIGene:643394","NCBIGene:81697","NCBIGene:55733","NCBIGene:4482","NCBIGene:7916","NCBIGene:63892","NCBIGene:80309","NCBIGene:79875","NCBIGene:79807","NCBIGene:6597","NCBIGene:55823","NCBIGene:57153","NCBIGene:26133","NCBIGene:3920","NCBIGene:92579","NCBIGene:10713","NCBIGene:10806","NCBIGene:23053","NCBIGene:516","NCBIGene:83874","NCBIGene:2169","NCBIGene:8829","NCBIGene:1284","NCBIGene:23316","NCBIGene:2038","NCBIGene:4739","NCBIGene:169792","NCBIGene:2983","NCBIGene:9575","NCBIGene:10786","NCBIGene:1909","NCBIGene:84072","NCBIGene:9076","NCBIGene:54622","NCBIGene:10020","NCBIGene:2982","NCBIGene:1136","NCBIGene:11118","NCBIGene:9260","NCBIGene:3240","NCBIGene:10107","NCBIGene:6188","NCBIGene:348938","NCBIGene:221692","NCBIGene:2628","NCBIGene:81577","NCBIGene:9570","NCBIGene:56241","NCBIGene:5684","NCBIGene:81619","NCBIGene:7078","NCBIGene:165215","NCBIGene:7056","NCBIGene:3156","NCBIGene:284076","NCBIGene:29113","NCBIGene:91754","NCBIGene:54828","NCBIGene:54535","NCBIGene:54658","NCBIGene:11261","NCBIGene:57211","NCBIGene:54454","NCBIGene:338","NCBIGene:10878","NCBIGene:245812","NCBIGene:6314","NCBIGene:646","NCBIGene:23384","NCBIGene:5048","NCBIGene:7168","NCBIGene:6444","NCBIGene:80737","NCBIGene:100631383","NCBIGene:8356","NCBIGene:9938","NCBIGene:143903","NCBIGene:5795","NCBIGene:84722","NCBIGene:64761","NCBIGene:10466","NCBIGene:6128","NCBIGene:2022","NCBIGene:8508","NCBIGene:123688","NCBIGene:9674","NCBIGene:144348","NCBIGene:9531","NCBIGene:2793","NCBIGene:7369","NCBIGene:3609","NCBIGene:342618","NCBIGene:401152","NCBIGene:91624","NCBIGene:1824","NCBIGene:649","NCBIGene:7122","NCBIGene:4624","NCBIGene:28964","NCBIGene:128611","NCBIGene:114821","NCBIGene:3913","NCBIGene:79029","NCBIGene:2070","NCBIGene:57419","NCBIGene:7718","NCBIGene:602","NCBIGene:255809","NCBIGene:80864","NCBIGene:6048","NCBIGene:9618","NCBIGene:4000","NCBIGene:84196","NCBIGene:3105","NCBIGene:57608","NCBIGene:8315","NCBIGene:81027","NCBIGene:3078","NCBIGene:23376","NCBIGene:171024","NCBIGene:268","NCBIGene:3009","NCBIGene:5819","NCBIGene:1788","NCBIGene:28","NCBIGene:80790","NCBIGene:10933","NCBIGene:7918","NCBIGene:7940","NCBIGene:10524","NCBIGene:79068","NCBIGene:8395","NCBIGene:64858","NCBIGene:7145","NCBIGene:2625","NCBIGene:85366","NCBIGene:7741","NCBIGene:4166","NCBIGene:63976","NCBIGene:286","NCBIGene:11044","NCBIGene:51322","NCBIGene:27332","NCBIGene:79696","NCBIGene:80321","NCBIGene:100528030","NCBIGene:2677","NCBIGene:7112","NCBIGene:11077","NCBIGene:1729","NCBIGene:56895","NCBIGene:80018","NCBIGene:51129","NCBIGene:8048","NCBIGene:23293","NCBIGene:53339","NCBIGene:6569","NCBIGene:55179","NCBIGene:5335","NCBIGene:3482","NCBIGene:97","NCBIGene:4015","NCBIGene:717","NCBIGene:85464","NCBIGene:58476","NCBIGene:406","NCBIGene:7273","NCBIGene:80724","NCBIGene:26707","NCBIGene:6499","NCBIGene:440275","NCBIGene:3250","NCBIGene:29128","NCBIGene:7414","NCBIGene:1026","NCBIGene:84547","NCBIGene:7746","NCBIGene:80776","NCBIGene:3897","NCBIGene:8348","NCBIGene:129303","NCBIGene:9862","NCBIGene:5878","NCBIGene:137682","NCBIGene:5781","NCBIGene:57644","NCBIGene:389118","NCBIGene:55249","NCBIGene:8354","NCBIGene:150864","NCBIGene:727","NCBIGene:6636","NCBIGene:57819","NCBIGene:10919","NCBIGene:644","NCBIGene:2120","NCBIGene:7703","NCBIGene:9837","NCBIGene:7745","NCBIGene:1762","NCBIGene:7840","NCBIGene:64240","NCBIGene:5978","NCBIGene:4627","NCBIGene:221955","NCBIGene:29956","NCBIGene:10211","NCBIGene:10554","NCBIGene:3728","NCBIGene:3122","NCBIGene:3949","NCBIGene:3236","NCBIGene:9869","NCBIGene:10665","NCBIGene:55101","NCBIGene:3930","NCBIGene:10877","NCBIGene:6441","NCBIGene:4829","NCBIGene:65264","NCBIGene:1394","NCBIGene:25802","NCBIGene:23255","NCBIGene:53916","NCBIGene:780","NCBIGene:2762","NCBIGene:79147","NCBIGene:8882","NCBIGene:2811","NCBIGene:2948","NCBIGene:51232","NCBIGene:4781","NCBIGene:6097","NCBIGene:54664","NCBIGene:55167","NCBIGene:1012","NCBIGene:6494","NCBIGene:50863","NCBIGene:57553","NCBIGene:5568","NCBIGene:55022","NCBIGene:64771","NCBIGene:23051","NCBIGene:55037","NCBIGene:8224","NCBIGene:51422","NCBIGene:84159","NCBIGene:29922","NCBIGene:80863","NCBIGene:53335","NCBIGene:490","NCBIGene:118663","NCBIGene:10060","NCBIGene:57404","NCBIGene:1282","NCBIGene:7472","NCBIGene:2017","NCBIGene:6581","NCBIGene:1071","NCBIGene:166815","NCBIGene:3119","NCBIGene:84273","NCBIGene:10287","NCBIGene:6708","NCBIGene:222962","NCBIGene:221527","NCBIGene:6891","NCBIGene:6238","NCBIGene:7139","NCBIGene:5699","NCBIGene:51686","NCBIGene:346","NCBIGene:7181","NCBIGene:10960","NCBIGene:63826","NCBIGene:10475","NCBIGene:22907","NCBIGene:199","NCBIGene:222696","NCBIGene:84315","NCBIGene:10677","NCBIGene:2812","NCBIGene:63891","NCBIGene:22978","NCBIGene:2119","NCBIGene:201176","NCBIGene:4128","NCBIGene:88","NCBIGene:4237","NCBIGene:10452","NCBIGene:7043","NCBIGene:659","NCBIGene:2845","NCBIGene:81846","NCBIGene:54814","NCBIGene:221545","NCBIGene:10498","NCBIGene:2590","NCBIGene:6457","NCBIGene:5089","NCBIGene:3171","NCBIGene:55973","NCBIGene:5664","NCBIGene:534","NCBIGene:79890","NCBIGene:374907","NCBIGene:3910","NCBIGene:23400","NCBIGene:408263","NCBIGene:55937","NCBIGene:8563","NCBIGene:10791","NCBIGene:10293","NCBIGene:147912","NCBIGene:5076","NCBIGene:23054","NCBIGene:1388","NCBIGene:8341","NCBIGene:6311","NCBIGene:2029","NCBIGene:124930","NCBIGene:29777","NCBIGene:1757","NCBIGene:6331","NCBIGene:8645","NCBIGene:6927","NCBIGene:4633","NCBIGene:3075","NCBIGene:64241","NCBIGene:9939","NCBIGene:1184","NCBIGene:84276","NCBIGene:124491","NCBIGene:8673","NCBIGene:8340","NCBIGene:388553","NCBIGene:11155","NCBIGene:283373","NCBIGene:1991","NCBIGene:50854","NCBIGene:6301","NCBIGene:204474","NCBIGene:154150","N [...]

2021-06-22 19:55 UTC, merged